name: Personal Website OCI CI

on:
  push: 
    branches: [ main ]
  workflow_dispatch:
    inputs: 
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs: 
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to OCI Compute
      env:
        DEPLOY_SCRIPT: ${{ secrets.DEPLOY_SCRIPT }} 
        PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
        PUBLIC_KEY: ${{ secrets.OCI_PUBLIC_KEY }}  
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      run: | 
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        echo "$PUBLIC_KEY" > public_key 
        bash -c "$DEPLOY_SCRIPT"
